package es.csc.biblioteca.customers.gui;

import es.csc.biblioteca.customers.dao.CustomerDTO;
import es.csc.biblioteca.i18n.LocaleManager;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.sql.Date;
import javax.swing.JInternalFrame;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author David Atencia
 * @version 0.1
 */
public class CustomersManagementView extends JInternalFrame {

    public CustomersManagementView() {
        initComponents();
        hideWarnings();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSplitPane1 = new javax.swing.JSplitPane();
        jPopupMenuCustomers = new javax.swing.JPopupMenu();
        jMenuItemAddCustomer = new javax.swing.JMenuItem();
        jMenuItemEditCustomer = new javax.swing.JMenuItem();
        jMenuItemDeleteCustomer = new javax.swing.JMenuItem();
        jLabel10 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnPreview = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomers = new javax.swing.JTable();
        lblId = new javax.swing.JLabel();
        lblDNI = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblCreationDate = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        dcCreationDate = new com.toedter.calendar.JDateChooser();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        lblWarningNIC = new javax.swing.JLabel();
        lblWarningFirstName = new javax.swing.JLabel();
        lblWarningLastName = new javax.swing.JLabel();
        lblWarningAddress = new javax.swing.JLabel();
        lblWarningDate = new javax.swing.JLabel();
        lblIdCustomer = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(200, 0), new java.awt.Dimension(200, 0), new java.awt.Dimension(200, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(100, 0), new java.awt.Dimension(100, 0), new java.awt.Dimension(100, 32767));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(100, 0), new java.awt.Dimension(100, 0), new java.awt.Dimension(100, 32767));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));

        jMenuItemAddCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/csc/biblioteca/customers/gui/resources/user1_add.png"))); // NOI18N
        jMenuItemAddCustomer.setText("jMenuItem1");
        jPopupMenuCustomers.add(jMenuItemAddCustomer);

        jMenuItemEditCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/csc/biblioteca/customers/gui/resources/user1_view.png"))); // NOI18N
        jMenuItemEditCustomer.setText("jMenuItem1");
        jPopupMenuCustomers.add(jMenuItemEditCustomer);

        jMenuItemDeleteCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/csc/biblioteca/customers/gui/resources/user1_delete.png"))); // NOI18N
        jMenuItemDeleteCustomer.setText("jMenuItem2");
        jPopupMenuCustomers.add(jMenuItemDeleteCustomer);

        setClosable(true);
        setIconifiable(true);
        setTitle("Customers Management");
        setMinimumSize(new java.awt.Dimension(800, 850));
        setPreferredSize(new java.awt.Dimension(800, 850));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel10.setBackground(new java.awt.Color(64, 64, 64));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/csc/biblioteca/customers/gui/resources/id_cards32.png"))); // NOI18N
        jLabel10.setText("Customers Management");
        jLabel10.setFocusable(false);
        jLabel10.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 8;
        getContentPane().add(jLabel10, gridBagConstraints);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/csc/biblioteca/customers/gui/resources/user1_add.png"))); // NOI18N
        btnAdd.setText("Add");
        btnAdd.setFocusable(false);
        btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnAdd);

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/csc/biblioteca/customers/gui/resources/user1_view.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setFocusable(false);
        btnEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnEdit);

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/csc/biblioteca/customers/gui/resources/user1_delete.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setFocusable(false);
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnDelete);
        jToolBar1.add(jSeparator1);

        btnPreview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/csc/biblioteca/customers/gui/resources/printer_view.png"))); // NOI18N
        btnPreview.setText("Preview");
        btnPreview.setFocusable(false);
        btnPreview.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPreview.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnPreview);

        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/csc/biblioteca/customers/gui/resources/printer.png"))); // NOI18N
        btnPrint.setText("Print");
        btnPrint.setFocusable(false);
        btnPrint.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPrint.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnPrint);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        getContentPane().add(jToolBar1, gridBagConstraints);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(600, 200));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(600, 200));

        tblCustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        tblCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCustomersMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblCustomersMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblCustomersMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblCustomers);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 0, 0);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        lblId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblId.setText("ID:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        getContentPane().add(lblId, gridBagConstraints);

        lblDNI.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDNI.setText("NIC:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        getContentPane().add(lblDNI, gridBagConstraints);

        lblFirstName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFirstName.setText("First Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        getContentPane().add(lblFirstName, gridBagConstraints);

        lblLastName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLastName.setText("Last Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        getContentPane().add(lblLastName, gridBagConstraints);

        lblAddress.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAddress.setText("Address:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        getContentPane().add(lblAddress, gridBagConstraints);

        lblCreationDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCreationDate.setText("Creation Date:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        getContentPane().add(lblCreationDate, gridBagConstraints);

        txtFirstName.setMinimumSize(new java.awt.Dimension(190, 18));
        txtFirstName.setName(""); // NOI18N
        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(txtFirstName, gridBagConstraints);

        txtLastName.setMinimumSize(new java.awt.Dimension(190, 18));
        txtLastName.setName(""); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(txtLastName, gridBagConstraints);

        txtAddress.setMinimumSize(new java.awt.Dimension(190, 18));
        txtAddress.setName(""); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(txtAddress, gridBagConstraints);

        dcCreationDate.setMaximumSize(new java.awt.Dimension(120, 20));
        dcCreationDate.setMinimumSize(new java.awt.Dimension(120, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(dcCreationDate, gridBagConstraints);

        btnOk.setText("Ok");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 13;
        getContentPane().add(btnOk, gridBagConstraints);

        btnCancel.setText("Cancel");
        btnCancel.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 13;
        getContentPane().add(btnCancel, gridBagConstraints);

        jLabel12.setBackground(new java.awt.Color(64, 64, 64));
        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/csc/biblioteca/customers/gui/resources/user1_view32.png"))); // NOI18N
        jLabel12.setText("Customer Details");
        jLabel12.setFocusable(false);
        jLabel12.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(jLabel12, gridBagConstraints);

        txtDNI.setToolTipText("");
        txtDNI.setAutoscrolls(false);
        txtDNI.setMinimumSize(new java.awt.Dimension(190, 18));
        txtDNI.setName(""); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(txtDNI, gridBagConstraints);

        lblWarningNIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/csc/biblioteca/customers/gui/resources/warning16.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(lblWarningNIC, gridBagConstraints);

        lblWarningFirstName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/csc/biblioteca/customers/gui/resources/warning16.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(lblWarningFirstName, gridBagConstraints);

        lblWarningLastName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/csc/biblioteca/customers/gui/resources/warning16.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(lblWarningLastName, gridBagConstraints);

        lblWarningAddress.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/csc/biblioteca/customers/gui/resources/warning16.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(lblWarningAddress, gridBagConstraints);

        lblWarningDate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/csc/biblioteca/customers/gui/resources/warning16.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(lblWarningDate, gridBagConstraints);

        lblIdCustomer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIdCustomer.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(lblIdCustomer, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.6;
        getContentPane().add(filler1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipady = 20;
        getContentPane().add(filler2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipady = 10;
        getContentPane().add(filler3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 6;
        gridBagConstraints.ipadx = 5;
        getContentPane().add(filler4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.ipadx = 5;
        getContentPane().add(filler5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 10;
        gridBagConstraints.ipadx = 180;
        getContentPane().add(filler6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipady = 20;
        getContentPane().add(filler7, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblCustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCustomersMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tblCustomersMouseClicked

    private void tblCustomersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCustomersMousePressed
    if (evt.isPopupTrigger()) {
        showPopupMenu(evt);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_tblCustomersMousePressed

    private void tblCustomersMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCustomersMouseReleased
    if (evt.isPopupTrigger()) {
        showPopupMenu(evt);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_tblCustomersMouseReleased

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnPreview;
    private javax.swing.JButton btnPrint;
    private com.toedter.calendar.JDateChooser dcCreationDate;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JMenuItem jMenuItemAddCustomer;
    private javax.swing.JMenuItem jMenuItemDeleteCustomer;
    private javax.swing.JMenuItem jMenuItemEditCustomer;
    private javax.swing.JPopupMenu jPopupMenuCustomers;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCreationDate;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblIdCustomer;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblWarningAddress;
    private javax.swing.JLabel lblWarningDate;
    private javax.swing.JLabel lblWarningFirstName;
    private javax.swing.JLabel lblWarningLastName;
    private javax.swing.JLabel lblWarningNIC;
    private javax.swing.JTable tblCustomers;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    // End of variables declaration//GEN-END:variables
 
    public void setPopupAddListener(ActionListener l, String command) {
        this.jMenuItemAddCustomer.addActionListener(l);
        this.jMenuItemAddCustomer.setActionCommand(command);
    }
    
    public void setPopupEditListener(ActionListener l, String command) {
        this.jMenuItemEditCustomer.addActionListener(l);
        this.jMenuItemEditCustomer.setActionCommand(command);
    }
    
    public void setPopupDeleteListener(ActionListener l, String command) {
        this.jMenuItemDeleteCustomer.addActionListener(l);
        this.jMenuItemDeleteCustomer.setActionCommand(command);
    }
    
    public void setAddListener(ActionListener l, String command) {
        this.btnAdd.addActionListener(l);
        this.btnAdd.setActionCommand(command);
    }
    
    public void setEditListener(ActionListener l, String command) {
        this.btnEdit.addActionListener(l);
        this.btnEdit.setActionCommand(command);
    }
    
    public void setDeleteListener(ActionListener l, String command) {
        this.btnDelete.addActionListener(l);
        this.btnDelete.setActionCommand(command);
    }
    
    public void setPrintListener(ActionListener l, String command) {
        this.btnPrint.addActionListener(l);
        this.btnPrint.setActionCommand(command);
    }
    
    public void setPreviewListener(ActionListener l, String command) {
        this.btnPreview.addActionListener(l);
        this.btnPreview.setActionCommand(command);
    }
    //Añadimos los dos nuevos botones
    public void setOkListener(ActionListener l, String command) {
        this.btnOk.addActionListener(l);
        this.btnOk.setActionCommand(command);
    } 
    public void setCancelListener(ActionListener l, String command) {
        this.btnCancel.addActionListener(l);
        this.btnCancel.setActionCommand(command);
    }
    
    public void setTableModel(AbstractTableModel m) {
        this.tblCustomers.setModel(m);
    }
    
    public void setRowSorter(TableRowSorter sorter) {
        this.tblCustomers.setRowSorter(sorter);
    }
    
    public int getSelectedRow() {
        if(this.tblCustomers.getSelectedRow()==-1)
        {
            return -1;
        }
        else
        {
            return this.tblCustomers.convertRowIndexToModel(this.tblCustomers.getSelectedRow());
        }
    }
    
    public void setSelectedRow(int indexRow) {
        int index = this.tblCustomers.convertRowIndexToView(indexRow);
        this.tblCustomers.setRowSelectionInterval(index, index);
    }

    private void showPopupMenu(MouseEvent e) {
        jPopupMenuCustomers.show(this, e.getX()+5, e.getY()+100);
    }    
    
    public void changeLanguage() {
        LocaleManager lm = LocaleManager.getInstance();
        this.setTitle(lm.getText("TITLE_CUSTOMERS_MANAGEMENT"));
        this.jLabel10.setText(lm.getText("TITLE_CUSTOMERS_MANAGEMENT"));
        this.btnAdd.setText(lm.getText("BUTTON_ADD"));
        this.btnEdit.setText(lm.getText("BUTTON_EDIT"));
        this.btnDelete.setText(lm.getText("BUTTON_DELETE"));
        this.btnPreview.setText(lm.getText("BUTTON_PREVIEW"));
        this.btnPrint.setText(lm.getText("BUTTON_PRINT"));
        this.jMenuItemAddCustomer.setText(lm.getText("MENU_POPUP_ADD"));
        this.jMenuItemEditCustomer.setText(lm.getText("MENU_POPUP_EDIT"));
        this.jMenuItemDeleteCustomer.setText(lm.getText("MENU_POPUP_DELETE"));
        
        //Añadimos la nueva parte
        this.setTitle(lm.getText("TITLE_CUSTOMER_DETAILS"));
        this.jLabel10.setText(lm.getText("TITLE_CUSTOMER_DETAILS"));
        this.lblDNI.setText(lm.getText("LABEL_DNI"));
        this.lblFirstName.setText(lm.getText("LABEL_FIRST_NAME"));
        this.lblLastName.setText(lm.getText("LABEL_LAST_NAME"));
        this.lblAddress.setText(lm.getText("LABEL_ADDRESS"));
        this.lblCreationDate.setText(lm.getText("LABEL_CREATION_DATE"));
        this.btnOk.setText(lm.getText("BUTTON_OK"));
        this.btnCancel.setText(lm.getText("BUTTON_CANCEL"));
    }
    
    //Añadimos las funciones que leen y escriben los campos de texto
    public CustomerDTO getCustomer() {
        CustomerDTO dto = new CustomerDTO();
        if (!"".equals(this.lblIdCustomer.getText())) {
            dto.setIdSocio(Integer.parseInt(this.lblIdCustomer.getText()));
        }
        dto.setNombre(this.txtFirstName.getText());
        dto.setApellidos(this.txtLastName.getText());
        dto.setDireccion(this.txtAddress.getText());
        dto.setDni(this.txtDNI.getText());
        if (this.dcCreationDate.getDate() != null) {
            dto.setFechaAlta(new Date(this.dcCreationDate.getDate().getTime()));
        }
        return dto;
    }
    
    public void hideWarnings() {
        this.lblWarningAddress.setVisible(false);
        this.lblWarningDate.setVisible(false);
        this.lblWarningFirstName.setVisible(false);
        this.lblWarningLastName.setVisible(false);
        this.lblWarningNIC.setVisible(false);
    }
    
    public void showWarningAddress(Boolean visible) {
        this.lblWarningAddress.setVisible(visible);
    }
    
    public void showWarningDate(Boolean visible) {
        this.lblWarningDate.setVisible(visible);
    }
    
    public void showWarningFirstName(Boolean visible) {
        this.lblWarningFirstName.setVisible(visible);
    }
    
    public void showWarningLastName(Boolean visible) {
        this.lblWarningLastName.setVisible(visible);
    }
    
    public void showWarningNIC(Boolean visible) {
        this.lblWarningNIC.setVisible(visible);
    }
    
    public void setCustomer(CustomerDTO customer) {
        if (customer == null) {
            this.dcCreationDate.setDate(new java.util.Date());
            this.lblIdCustomer.setText(null);
            this.txtFirstName.setText(null);
            this.txtLastName.setText(null);
            this.txtDNI.setText(null);
            this.txtAddress.setText(null);
            this.dcCreationDate.setDate(null);
        } else {
            this.lblIdCustomer.setText(String.valueOf(customer.getIdSocio()));
            this.txtFirstName.setText(customer.getNombre());
            this.txtLastName.setText(customer.getApellidos());
            this.txtDNI.setText(customer.getDni());
            this.txtAddress.setText(customer.getDireccion());
            this.dcCreationDate.setDate(customer.getFechaAlta());
        }
    }
    //Borrar
    public void borrar() {
        this.dcCreationDate.setDate(new java.util.Date());
        this.lblIdCustomer.setText(null);
        this.txtFirstName.setText(null);
        this.txtLastName.setText(null);
        this.txtDNI.setText(null);
        this.txtAddress.setText(null);
        this.dcCreationDate.setDate(null);
    }
}
