
package servlets.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.7
 * Tue Nov 05 23:06:48 CET 2013
 * Generated source version: 2.7.7
 */

@XmlRootElement(name = "SoapSearchResponse", namespace = "http://servlets/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SoapSearchResponse", namespace = "http://servlets/")

public class SoapSearchResponse {

    @XmlElement(name = "return")
    private beans.Search _return;

    public beans.Search getReturn() {
        return this._return;
    }

    public void setReturn(beans.Search new_return)  {
        this._return = new_return;
    }

}

