<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://infraestructura.healthworldbank.java.master.uned.es" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://infraestructura.healthworldbank.java.master.uned.es" xmlns:intf="http://infraestructura.healthworldbank.java.master.uned.es" xmlns:tns1="http://comunicacion.healthworldbank.java.master.uned.es" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
  <schema elementFormDefault="qualified" targetNamespace="http://infraestructura.healthworldbank.java.master.uned.es" xmlns="http://www.w3.org/2001/XMLSchema">
   <import namespace="http://comunicacion.healthworldbank.java.master.uned.es"/>
   <element name="getObtenerDatos">
    <complexType/>
   </element>
   <element name="getObtenerDatosResponse">
    <complexType>
     <sequence>
      <element name="getObtenerDatosReturn" type="xsd:anyType"/>
     </sequence>
    </complexType>
   </element>
  </schema>
 </wsdl:types>

   <wsdl:message name="getObtenerDatosResponse">

      <wsdl:part element="impl:getObtenerDatosResponse" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="getObtenerDatosRequest">

      <wsdl:part element="impl:getObtenerDatos" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:portType name="DatosHealthWorldBank">

      <wsdl:operation name="getObtenerDatos">

         <wsdl:input message="impl:getObtenerDatosRequest" name="getObtenerDatosRequest">

       </wsdl:input>

         <wsdl:output message="impl:getObtenerDatosResponse" name="getObtenerDatosResponse">

       </wsdl:output>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="DatosHealthWorldBankSoapBinding" type="impl:DatosHealthWorldBank">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="getObtenerDatos">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="getObtenerDatosRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="getObtenerDatosResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="DatosHealthWorldBankService">

      <wsdl:port binding="impl:DatosHealthWorldBankSoapBinding" name="DatosHealthWorldBank">

         <wsdlsoap:address location="http://localhost:8080/HealthWorldBankWS/services/DatosHealthWorldBank"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
