/*
 * Generated by XDoclet - Do not edit!
 */
package com.prueba.ejb;

/**
 * Local interface for Hola.
 * @generated 
 * @wtp generated
 */
public interface HolaLocal
   extends javax.ejb.EJBLocalObject
{

}
