/*
 * Generated by XDoclet - Do not edit!
 */
package com.prueba.ejb;

/**
 * Remote interface for Hola.
 * @generated 
 * @wtp generated
 */
public interface Hola
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public java.lang.String hola(  )
      throws java.rmi.RemoteException;

}
