
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package es.uned.sw;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-09-12T19:01:38.064+02:00
 * Generated source version: 2.7.12
 * 
 */

@javax.jws.WebService(
                      serviceName = "CuentasService",
                      portName = "CuentasPort",
                      targetNamespace = "http://sw.uned.es/",
                      wsdlLocation = "http://localhost:8080/JAX_Servidor/services/CuentasPort?wsdl",
                      endpointInterface = "es.uned.sw.Cuentas")
                      
public class CuentasImpl implements Cuentas {

    private static final Logger LOG = Logger.getLogger(CuentasImpl.class.getName());

    /* (non-Javadoc)
     * @see es.uned.sw.Cuentas#sumar(int  arg0 ,)int  arg1 )*
     */
    public java.lang.String sumar(int arg0,int arg1) { 
        LOG.info("Executing operation sumar");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "_return-952316358";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
