package es.uned.sw;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-09-12T19:01:38.085+02:00
 * Generated source version: 2.7.12
 * 
 */
@WebService(targetNamespace = "http://sw.uned.es/", name = "Cuentas")
@XmlSeeAlso({ObjectFactory.class})
public interface Cuentas {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sumar", targetNamespace = "http://sw.uned.es/", className = "es.uned.sw.Sumar")
    @WebMethod
    @ResponseWrapper(localName = "sumarResponse", targetNamespace = "http://sw.uned.es/", className = "es.uned.sw.SumarResponse")
    public java.lang.String sumar(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );
}
