
package es.uned.sw;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-09-12T19:01:37.978+02:00
 * Generated source version: 2.7.12
 * 
 */
public final class Cuentas_CuentasPort_Client {

    private static final QName SERVICE_NAME = new QName("http://sw.uned.es/", "CuentasService");

    private Cuentas_CuentasPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CuentasService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CuentasService ss = new CuentasService(wsdlURL, SERVICE_NAME);
        Cuentas port = ss.getCuentasPort();  
        
        {
        System.out.println("Invoking sumar...");
        int _sumar_arg0 = 822845652;
        int _sumar_arg1 = 1088697451;
        java.lang.String _sumar__return = port.sumar(_sumar_arg0, _sumar_arg1);
        System.out.println("sumar.result=" + _sumar__return);


        }

        System.exit(0);
    }

}
