<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="WSSoapService" targetNamespace="http://servlets/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://servlets/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
  <import namespace="http://servlets/" schemaLocation="wssoap_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="SoapSearchResponse">
    <wsdl:part name="parameters" element="tns:SoapSearchResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="SoapSearch">
    <wsdl:part name="parameters" element="tns:SoapSearch">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="WSSoap">
    <wsdl:operation name="SoapSearch">
      <wsdl:input name="SoapSearch" message="tns:SoapSearch">
    </wsdl:input>
      <wsdl:output name="SoapSearchResponse" message="tns:SoapSearchResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="WSSoapServiceSoapBinding" type="tns:WSSoap">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="SoapSearch">
      <soap:operation soapAction="urn:SoapSearch" style="document"/>
      <wsdl:input name="SoapSearch">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="SoapSearchResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="WSSoapService">
    <wsdl:port name="WSSoapPort" binding="tns:WSSoapServiceSoapBinding">
      <soap:address location="http://localhost:8080/MedLineBennett2.2Server/services/WSSoapPort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
