/**
 * Gestión básica de una biblioteca.
 * @author Antonio Dorado
 * @version 1.0 - 17/11/2015
 */

package com.csc.biblioteca.mdi;

import com.csc.biblioteca.util.Messages;

/**
 * Ventana "Acercade" con información sobre la aplicación.
 */
public class AcercadeVista extends javax.swing.JInternalFrame {

    /**
     * Constructor de la ventana.
     * @param titulo Título de la ventana.
     */
    public AcercadeVista(String titulo) {
        super(titulo, false, true, false, false);   // title, resizable, closable, maximizable, iconifiable
        this.initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblAplicacion = new javax.swing.JLabel();
        lblCurso = new javax.swing.JLabel();
        lblAutor = new javax.swing.JLabel();
        lblAplicacionValor = new javax.swing.JLabel();
        lblCursoValor = new javax.swing.JLabel();
        lblAutorValor = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblFechaValor = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        jpnNorte = new javax.swing.JPanel();
        jpnOeste = new javax.swing.JPanel();
        jpnEste = new javax.swing.JPanel();
        jpnSur = new javax.swing.JPanel();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        lblAplicacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAplicacion.setText(Messages.getString("ETQ_ABOUT_APLICACION")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(lblAplicacion, gridBagConstraints);

        lblCurso.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCurso.setText(Messages.getString("ETQ_ABOUT_CURSO")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(lblCurso, gridBagConstraints);

        lblAutor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAutor.setText(Messages.getString("ETQ_ABOUT_AUTOR")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(lblAutor, gridBagConstraints);

        lblAplicacionValor.setForeground(new java.awt.Color(0, 0, 255));
        lblAplicacionValor.setText(Messages.getString("ETQ_ABOUT_DESCRIPCION")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(lblAplicacionValor, gridBagConstraints);

        lblCursoValor.setForeground(new java.awt.Color(0, 0, 255));
        lblCursoValor.setText("Java Swing 2015-T1 @ CSC");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(lblCursoValor, gridBagConstraints);

        lblAutorValor.setForeground(new java.awt.Color(0, 0, 255));
        lblAutorValor.setText("Antonio Dorado Ruíz");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(lblAutorValor, gridBagConstraints);

        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFecha.setText(Messages.getString("ETQ_ABOUT_FECHA")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(lblFecha, gridBagConstraints);

        lblFechaValor.setForeground(new java.awt.Color(0, 0, 255));
        lblFechaValor.setText("17/12/2015");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(lblFechaValor, gridBagConstraints);

        btnCerrar.setText(Messages.getString("BOTON_CERRAR")); // NOI18N
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCerrar.setMaximumSize(new java.awt.Dimension(71, 23));
        btnCerrar.setMinimumSize(new java.awt.Dimension(71, 23));
        btnCerrar.setPreferredSize(new java.awt.Dimension(71, 23));
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(btnCerrar, gridBagConstraints);

        jpnNorte.setMinimumSize(new java.awt.Dimension(300, 0));
        jpnNorte.setPreferredSize(new java.awt.Dimension(300, 20));

        javax.swing.GroupLayout jpnNorteLayout = new javax.swing.GroupLayout(jpnNorte);
        jpnNorte.setLayout(jpnNorteLayout);
        jpnNorteLayout.setHorizontalGroup(
            jpnNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jpnNorteLayout.setVerticalGroup(
            jpnNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 0.5;
        getContentPane().add(jpnNorte, gridBagConstraints);

        jpnOeste.setPreferredSize(new java.awt.Dimension(20, 100));

        javax.swing.GroupLayout jpnOesteLayout = new javax.swing.GroupLayout(jpnOeste);
        jpnOeste.setLayout(jpnOesteLayout);
        jpnOesteLayout.setHorizontalGroup(
            jpnOesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpnOesteLayout.setVerticalGroup(
            jpnOesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        getContentPane().add(jpnOeste, gridBagConstraints);

        jpnEste.setPreferredSize(new java.awt.Dimension(20, 100));

        javax.swing.GroupLayout jpnEsteLayout = new javax.swing.GroupLayout(jpnEste);
        jpnEste.setLayout(jpnEsteLayout);
        jpnEsteLayout.setHorizontalGroup(
            jpnEsteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpnEsteLayout.setVerticalGroup(
            jpnEsteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        getContentPane().add(jpnEste, gridBagConstraints);

        jpnSur.setMinimumSize(new java.awt.Dimension(0, 10));
        jpnSur.setPreferredSize(new java.awt.Dimension(0, 10));

        javax.swing.GroupLayout jpnSurLayout = new javax.swing.GroupLayout(jpnSur);
        jpnSur.setLayout(jpnSurLayout);
        jpnSurLayout.setHorizontalGroup(
            jpnSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpnSurLayout.setVerticalGroup(
            jpnSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        getContentPane().add(jpnSur, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.doDefaultCloseAction();
    }//GEN-LAST:event_btnCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JPanel jpnEste;
    private javax.swing.JPanel jpnNorte;
    private javax.swing.JPanel jpnOeste;
    private javax.swing.JPanel jpnSur;
    private javax.swing.JLabel lblAplicacion;
    private javax.swing.JLabel lblAplicacionValor;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblAutorValor;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblCursoValor;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFechaValor;
    // End of variables declaration//GEN-END:variables
}
