
package uned.java2016.apitwitter.services.soap.estudios;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EstudioService", targetNamespace = "http://estudios.soap.services.apitwitter.java2016.uned/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EstudioService {


    /**
     * 
     * @param nct
     * @return
     *     returns uned.java2016.apitwitter.services.soap.estudios.ClinicalStudy
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getByNCT", targetNamespace = "http://estudios.soap.services.apitwitter.java2016.uned/", className = "uned.java2016.apitwitter.services.soap.estudios.GetByNCT")
    @ResponseWrapper(localName = "getByNCTResponse", targetNamespace = "http://estudios.soap.services.apitwitter.java2016.uned/", className = "uned.java2016.apitwitter.services.soap.estudios.GetByNCTResponse")
    @Action(input = "http://estudios.soap.services.apitwitter.java2016.uned/EstudioService/getByNCTRequest", output = "http://estudios.soap.services.apitwitter.java2016.uned/EstudioService/getByNCTResponse")
    public ClinicalStudy getByNCT(
        @WebParam(name = "nct", targetNamespace = "")
        String nct);

    /**
     * 
     * @param count
     * @param hashtag
     * @return
     *     returns uned.java2016.apitwitter.services.soap.estudios.Estudios
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getByHashtag", targetNamespace = "http://estudios.soap.services.apitwitter.java2016.uned/", className = "uned.java2016.apitwitter.services.soap.estudios.GetByHashtag")
    @ResponseWrapper(localName = "getByHashtagResponse", targetNamespace = "http://estudios.soap.services.apitwitter.java2016.uned/", className = "uned.java2016.apitwitter.services.soap.estudios.GetByHashtagResponse")
    @Action(input = "http://estudios.soap.services.apitwitter.java2016.uned/EstudioService/getByHashtagRequest", output = "http://estudios.soap.services.apitwitter.java2016.uned/EstudioService/getByHashtagResponse")
    public Estudios getByHashtag(
        @WebParam(name = "hashtag", targetNamespace = "")
        String hashtag,
        @WebParam(name = "count", targetNamespace = "")
        int count);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "echo", targetNamespace = "http://estudios.soap.services.apitwitter.java2016.uned/", className = "uned.java2016.apitwitter.services.soap.estudios.Echo")
    @ResponseWrapper(localName = "echoResponse", targetNamespace = "http://estudios.soap.services.apitwitter.java2016.uned/", className = "uned.java2016.apitwitter.services.soap.estudios.EchoResponse")
    @Action(input = "http://estudios.soap.services.apitwitter.java2016.uned/EstudioService/echoRequest", output = "http://estudios.soap.services.apitwitter.java2016.uned/EstudioService/echoResponse")
    public String echo();

}
