package servlets;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-11-06T20:24:20.660+01:00
 * Generated source version: 2.7.7
 * 
 */
@WebServiceClient(name = "WSSoapService", 
                  wsdlLocation = "file:/C:/Users/Paco/workspace/MedLineBennett2.2Server/WebContent/wsdl/wssoap.wsdl",
                  targetNamespace = "http://servlets/") 
public class WSSoapService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://servlets/", "WSSoapService");
    public final static QName WSSoapPort = new QName("http://servlets/", "WSSoapPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Paco/workspace/MedLineBennett2.2Server/WebContent/wsdl/wssoap.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WSSoapService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Paco/workspace/MedLineBennett2.2Server/WebContent/wsdl/wssoap.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WSSoapService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSSoapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSSoapService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSSoapService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSSoapService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSSoapService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns WSSoap
     */
    @WebEndpoint(name = "WSSoapPort")
    public WSSoap getWSSoapPort() {
        return super.getPort(WSSoapPort, WSSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSSoap
     */
    @WebEndpoint(name = "WSSoapPort")
    public WSSoap getWSSoapPort(WebServiceFeature... features) {
        return super.getPort(WSSoapPort, WSSoap.class, features);
    }

}
