/*
 * Generated by XDoclet - Do not edit!
 */
package com.prueba.ejb;

/**
 * Home interface for Hola.
 * @generated 
 * @wtp generated
 */
public interface HolaHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/Hola";
   public static final String JNDI_NAME="Hola";

   public com.prueba.ejb.Hola create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
