/*
 * Generated by XDoclet - Do not edit!
 */
package com.prueba.ejb;

/**
 * Local home interface for Hola.
 * @generated 
 * @wtp generated
 */
public interface HolaLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/HolaLocal";
   public static final String JNDI_NAME="HolaLocal";

   public com.prueba.ejb.HolaLocal create()
      throws javax.ejb.CreateException;

}
