FROM tomcat:9.0
#COPY ./target/carritoCompra-0.0.1.war /usr/local/tomcat/webapps/carritoCompra.war
COPY ./target/miPrimerBonitoServlet-0.0.1.war /usr/local/tomcat/webapps/
CMD ["catalina.sh", "run"]
EXPOSE 8080