
package uned.java2016.apitwitter.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NeighbourService", targetNamespace = "http://services.apitwitter.java2016.uned/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NeighbourService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "echo", targetNamespace = "http://services.apitwitter.java2016.uned/", className = "uned.java2016.apitwitter.services.Echo")
    @ResponseWrapper(localName = "echoResponse", targetNamespace = "http://services.apitwitter.java2016.uned/", className = "uned.java2016.apitwitter.services.EchoResponse")
    @Action(input = "http://services.apitwitter.java2016.uned/NeighbourService/echoRequest", output = "http://services.apitwitter.java2016.uned/NeighbourService/echoResponse")
    public String echo();

    /**
     * 
     * @param hashtag
     * @return
     *     returns uned.java2016.apitwitter.services.Neighbours
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNeighbours", targetNamespace = "http://services.apitwitter.java2016.uned/", className = "uned.java2016.apitwitter.services.GetNeighbours")
    @ResponseWrapper(localName = "getNeighboursResponse", targetNamespace = "http://services.apitwitter.java2016.uned/", className = "uned.java2016.apitwitter.services.GetNeighboursResponse")
    @Action(input = "http://services.apitwitter.java2016.uned/NeighbourService/getNeighboursRequest", output = "http://services.apitwitter.java2016.uned/NeighbourService/getNeighboursResponse")
    public Neighbours getNeighbours(
        @WebParam(name = "hashtag", targetNamespace = "")
        String hashtag);

}
