package es.csc.biblioteca.books.gui;

import es.csc.biblioteca.books.dao.BookDTO;
import es.csc.biblioteca.i18n.LocaleManager;
import java.awt.event.ActionListener;

/**
 *
 * @author David Atencia
 * @version 0.1
 */
public class BookDetailsView extends javax.swing.JDialog {

    public BookDetailsView() {
        initComponents();
        hideWarnings();
    }

    public void setOkListener(ActionListener l, String command) {
        this.btnOk.addActionListener(l);
        this.btnOk.setActionCommand(command);
    }
    
    public void setCancelListener(ActionListener l, String command) {
        this.btnCancel.addActionListener(l);
        this.btnCancel.setActionCommand(command);
    }
    
    public void setBook(BookDTO book) {
        if (book != null) {
            this.lblIdBook.setText(String.valueOf(book.getIdLibro()));
            this.txtTitle.setText(book.getNombre());
            this.txtAuthor.setText(book.getAutor());
            this.txtTopic.setText(book.getTema());
        }
    }
    
    public BookDTO getBook() {
        BookDTO dto = new BookDTO();
        if (!"".equals(this.lblIdBook.getText())) {
            dto.setIdLibro(Integer.parseInt(this.lblIdBook.getText()));
        }
        dto.setNombre(this.txtTitle.getText());
        dto.setAutor(this.txtAuthor.getText());
        dto.setTema(this.txtTopic.getText());
        return dto;
    }
    
    public void translate() {
        LocaleManager lm = LocaleManager.getInstance();
        this.setTitle(lm.getText("TITLE_BOOK_DETAILS"));
        this.jLabel10.setText(lm.getText("TITLE_BOOK_DETAILS"));
        this.lblTitle.setText(lm.getText("LABEL_TITLE"));
        this.lblAuthor.setText(lm.getText("LABEL_AUTHOR"));
        this.lblTopic.setText(lm.getText("LABEL_TOPIC"));
        this.btnOk.setText(lm.getText("BUTTON_OK"));
        this.btnCancel.setText(lm.getText("BUTTON_CANCEL"));
    }
    
    public void hideWarnings() {
        this.lblWarningTitle.setVisible(false);
        this.lblWarningAuthor.setVisible(false);
        this.lblWarningTopic.setVisible(false);
    }
    
    public void showWarningTitle(Boolean visible) {
        this.lblWarningTitle.setVisible(visible);
    }
    
    public void showWarningAuthor(Boolean visible) {
        this.lblWarningAuthor.setVisible(visible);
    }
    
    public void showWarningTopic(Boolean visible) {
        this.lblWarningTopic.setVisible(visible);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblId = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblAuthor = new javax.swing.JLabel();
        lblTopic = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        txtAuthor = new javax.swing.JTextField();
        txtTopic = new javax.swing.JTextField();
        lblIdBook = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblWarningTitle = new javax.swing.JLabel();
        lblWarningTopic = new javax.swing.JLabel();
        lblWarningAuthor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Book Details");
        setModal(true);
        setResizable(false);

        lblId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblId.setText("ID:");

        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTitle.setText("Title:");

        lblAuthor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAuthor.setText("Author:");

        lblTopic.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTopic.setText("Topic:");

        lblIdBook.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        btnOk.setText("Ok");

        btnCancel.setText("Cancel");

        jLabel10.setBackground(new java.awt.Color(64, 64, 64));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/csc/biblioteca/books/gui/resources/book_view32.png"))); // NOI18N
        jLabel10.setText("Book Details");
        jLabel10.setFocusable(false);
        jLabel10.setOpaque(true);

        lblWarningTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/csc/biblioteca/customers/gui/resources/warning16.png"))); // NOI18N

        lblWarningTopic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/csc/biblioteca/customers/gui/resources/warning16.png"))); // NOI18N

        lblWarningAuthor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/csc/biblioteca/customers/gui/resources/warning16.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                            .addComponent(lblTopic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTopic)
                            .addComponent(txtTitle)
                            .addComponent(lblIdBook, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                            .addComponent(txtAuthor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblWarningTopic)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblWarningAuthor)
                                .addComponent(lblWarningTitle))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 238, Short.MAX_VALUE)
                        .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblId)
                    .addComponent(lblIdBook, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWarningTitle)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblTitle))
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAuthor)
                        .addComponent(txtAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblWarningAuthor))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lblTopic))
                            .addComponent(txtTopic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOk)
                            .addComponent(btnCancel)))
                    .addComponent(lblWarningTopic))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAuthor;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblIdBook;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTopic;
    private javax.swing.JLabel lblWarningAuthor;
    private javax.swing.JLabel lblWarningTitle;
    private javax.swing.JLabel lblWarningTopic;
    private javax.swing.JTextField txtAuthor;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JTextField txtTopic;
    // End of variables declaration//GEN-END:variables

}
