
package servlets;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-11-06T20:24:20.476+01:00
 * Generated source version: 2.7.7
 * 
 */
public final class WSSoap_WSSoapPort_Client {

    private static final QName SERVICE_NAME = new QName("http://servlets/", "WSSoapService");

    private WSSoap_WSSoapPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WSSoapService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WSSoapService ss = new WSSoapService(wsdlURL, SERVICE_NAME);
        WSSoap port = ss.getWSSoapPort();  
        
        {
        System.out.println("Invoking soapSearch...");
        int _soapSearch_arg0 = -1650106956;
        java.lang.String _soapSearch_arg1 = "_soapSearch_arg1-1850998776";
        java.lang.String _soapSearch_arg2 = "_soapSearch_arg2-2067922572";
        java.lang.String _soapSearch_arg3 = "_soapSearch_arg31676330170";
        servlets.Search _soapSearch__return = port.soapSearch(_soapSearch_arg0, _soapSearch_arg1, _soapSearch_arg2, _soapSearch_arg3);
        System.out.println("soapSearch.result=" + _soapSearch__return);


        }

        System.exit(0);
    }

}
