package servlets;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-11-06T20:24:20.646+01:00
 * Generated source version: 2.7.7
 * 
 */
@WebService(targetNamespace = "http://servlets/", name = "WSSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface WSSoap {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "SoapSearch", targetNamespace = "http://servlets/", className = "servlets.SoapSearch")
    @WebMethod(operationName = "SoapSearch", action = "urn:SoapSearch")
    @ResponseWrapper(localName = "SoapSearchResponse", targetNamespace = "http://servlets/", className = "servlets.SoapSearchResponse")
    public servlets.Search soapSearch(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );
}
