
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package servlets;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-11-06T20:24:20.621+01:00
 * Generated source version: 2.7.7
 * 
 */

@javax.jws.WebService(
                      serviceName = "WSSoapService",
                      portName = "WSSoapPort",
                      targetNamespace = "http://servlets/",
                      wsdlLocation = "file:/C:/Users/Paco/workspace/MedLineBennett2.2Server/WebContent/wsdl/wssoap.wsdl",
                      endpointInterface = "servlets.WSSoap")
                      
public class WSSoapImpl implements WSSoap {

    private static final Logger LOG = Logger.getLogger(WSSoapImpl.class.getName());

    /* (non-Javadoc)
     * @see servlets.WSSoap#soapSearch(int  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 ,)java.lang.String  arg3 )*
     */
    public servlets.Search soapSearch(int arg0,java.lang.String arg1,java.lang.String arg2,java.lang.String arg3) { 
        LOG.info("Executing operation soapSearch");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        try {
            servlets.Search _return = new servlets.Search();
            java.util.List<java.lang.String> _returnTitle = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnTitleVal1 = "_returnTitleVal-1634668063";
            _returnTitle.add(_returnTitleVal1);
            _return.getTitle().addAll(_returnTitle);
            java.util.List<java.lang.String> _returnURL = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnURLVal1 = "_returnURLVal113107039";
            _returnURL.add(_returnURLVal1);
            _return.getURL().addAll(_returnURL);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
